### ISSUE TITLE
Are ILP 32 and ILP 64 correct?

### ISSUE THREAD

**Issue by WilliamWangPeng** [boegel/MICA#23]
Hi dear authors,   
    I'm using MICA to test hello ELF, the ilp.out are as following here:  
    
![image](https://user-images.githubusercontent.com/51076736/117813817-20333f00-b296-11eb-9a6a-803282770458.png)    

hello.cpp
#include <iostream> using namespace std; main() { cout << "Hello World"; return 0; }  

where  578058 is ILP 32???  
the source code in mica_ilp.cpp shows cpuClock_interval_all[0]=  578058.   

so what is the correct value of ILP32?

thank you  
best regards  
William

**Comment by amirjamez** [comment]
It would be best to trace the source code and see which one outputs which metrics: 

https://github.com/boegel/MICA/blob/master/mica_ilp.cpp

Check for lines with `output_file_ilp_one .open()` and change/rename them to your preferred name so that you can pinpoint them in the csv file. Remember to recompile the project first.
